### ISSUE TITLE
The navigator is too eager to find occurences of immutable builder property setters

### ISSUE THREAD

**Issue by fkalinski** [plaskowski/find-immutables-usages-plugin#2]
Great plugin! Was looking for something like this for some time!

I've found one issue. For the code
```@Value.Immutable(intern = true)
public interface OrderReasonImpl extends OrderReason {
	@Override
	@Value.Parameter
	String code(); // <-- navigation to usages from here
}
```
usages of hashCode() method all around the project are found.

**Comment by plaskowski** [comment]
Thank you for creating the issue.
I'm happy to hear that you find the plugin useful.

The current implementation looks at all implementation class methods and picks those fulfilling ``method.name.contains(propertyName)`` to support various naming styles.

The correct solution would be to support the ``Value.Style`` in the correct, precise way, but in the mean time I may patch the implementation in following ways (inspired by your case):
* exclude no-arg methods as they are not setters
  * this will exclude the getter implementation but it seems acceptable as it is rather not of an interest in interface method 'Find Usages' context
* exclude any inherited methods as we are interested only in generated methods
  * however I have first check how it fits "abstract class" case and default methods in super interface

**Comment by fkalinski** [comment]
Thanks for reply and the fix.
